INSERT INTO roles (role_name)Values('principal');
INSERT INTO roles (role_name)VALUES('coordinator');
INSERT INTO roles (role_name)VALUES('trip leader');
INSERT INTO roles (role_name)VALUES('teacher');
INSERT INTO statuses(status_name)VALUES("schedualed");
INSERT INTO statuses(status_name)VALUES("approved");
INSERT INTO statuses(status_name)VALUES ("closed");
INSERT INTO emergency_types (type_name, severity_level) VALUES ('minor', 1);
INSERT INTO emergency_types (type_name, severity_level) VALUES ('critical', 2);
INSERT INTO file_codes (file_name) VALUES ("מינוי אחראי טיול");
INSERT INTO file_codes (file_name) VALUES ("אישור יציאה לטיול ממנהל מוסד");
INSERT INTO file_codes (file_name) VALUES ("אישורי הורים");
INSERT INTO file_codes (file_name) VALUES ("רשימת תלמידים");
INSERT INTO file_codes (file_name) VALUES ("רשימת תלמידים עם מגבלות רפואיות");
INSERT INTO file_codes (file_name) VALUES ("טופס הפניה לטיפול רפואי לתלמיד שנפגע במהלך טיול");
INSERT INTO file_codes (file_name) VALUES ("רשימת תלמידים שנפגעו במהלך טיול");
INSERT INTO file_codes (file_name) VALUES ("טופס ביטוח למתנדב");
INSERT INTO file_codes (file_name) VALUES ("רשימת מלווים וטלפונים חיוניים בטיול");
INSERT INTO file_codes (file_name) VALUES ("הנחיות למורה אחראי כיתה");
INSERT INTO file_codes (file_name) VALUES ("טופס תיאום טיולים מאושר");
INSERT INTO emergency_status (status_code,status_name) VALUES (1,"open");
INSERT INTO emergency_status (status_code,status_name) VALUES (2,"closed");
INSERT INTO external_role(role_name)VALUES("guard");
INSERT INTO external_role(role_name)VALUES("medic");
INSERT INTO external_role(role_name)VALUES("paramedic");
INSERT INTO external_role(role_name)VALUES("guide");
INSERT INTO external_role(role_name)VALUES("first-aid-provider");